apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: continuous-deployment
  namespace: self-hosted-runners
rules:
  - apiGroups:
      - ''
      - apps
      - networking.k8s.io
    resources:
      - namespaces
      - deployments
      - replicasets
      - ingresses
      - services
      - secrets
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gh-agent-argocd
  namespace: self-hosted-runners
roleRef:
  kind: Role
  name: continuous-deployment
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: default # Name is case sensitive
  namespace: self-hosted-runners